{
  "type": "issue",
  "issue": {
    "id": 2390290074,
    "node_id": "I_kwDOABII586OeO6a",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/30390",
    "number": 30390,
    "state": "open",
    "state_reason": null,
    "title": "ci: ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it",
    "body": "Usually they come with a follow-up error of `Unable to connect to bitcoind after 2400s` (or similar).\r\n\r\nThis is a tracking issue, because all tests are affected.",
    "user": {
      "login": "maflcko",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maflcko",
      "html_url": "https://github.com/maflcko",
      "followers_url": "https://api.github.com/users/maflcko/followers",
      "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
      "organizations_url": "https://api.github.com/users/maflcko/orgs",
      "repos_url": "https://api.github.com/users/maflcko/repos",
      "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/maflcko/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 234877,
        "node_id": "MDU6TGFiZWwyMzQ4Nzc=",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
        "name": "Windows",
        "color": "884400",
        "default": false
      },
      {
        "id": 62963516,
        "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
        "name": "Tests",
        "color": "d4c5f9",
        "default": false
      },
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 12,
    "created_at": "2024-07-04T08:40:22Z",
    "updated_at": "2024-08-27T09:51:06Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 13391441572,
      "node_id": "LE_lADOABII586OeO6azwAAAAMeMS6k",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/13391441572",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T08:40:22Z",
      "label": {
        "name": "Windows",
        "color": "884400"
      }
    },
    {
      "event": "labeled",
      "id": 13391441582,
      "node_id": "LE_lADOABII586OeO6azwAAAAMeMS6u",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/13391441582",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T08:40:22Z",
      "label": {
        "name": "Tests",
        "color": "d4c5f9"
      }
    },
    {
      "event": "labeled",
      "id": 13391441587,
      "node_id": "LE_lADOABII586OeO6azwAAAAMeMS6z",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/13391441587",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T08:40:22Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    },
    {
      "event": "commented",
      "id": 2208589062,
      "node_id": "IC_kwDOABII586DpGUG",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2208589062",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-04T09:59:39Z",
      "updated_at": "2024-07-04T09:59:39Z",
      "author_association": "MEMBER",
      "body": "Given that no one has reproduced this locally yet, this may be an issue limited to GHA.",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2208589062",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2219919953,
      "node_id": "IC_kwDOABII586EUUpR",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2219919953",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-07-10T08:45:08Z",
      "updated_at": "2024-07-10T08:45:08Z",
      "author_association": "MEMBER",
      "body": "Seen recently here (`wallet_bumpfee.py --descriptors`) https://github.com/bitcoin/bitcoin/actions/runs/9863555844/job/27236587622#step:27:12496:\r\n```bash\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 188, in _raise_assertion_error\r\n                                       raise AssertionError(self._node_msg(msg))\r\n                                   AssertionError: [node 1] Unable to connect to bitcoind after 2400s\r\n test  2024-07-09T21:07:49.462000Z TestFramework (DEBUG): Closing down network thread \r\n```",
      "user": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2219919953",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311170636,
      "node_id": "IC_kwDOABII586JwapM",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311170636",
      "actor": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-26T21:56:08Z",
      "updated_at": "2024-08-27T07:30:13Z",
      "author_association": "CONTRIBUTOR",
      "body": "Would something like this be useful in helping approach the root cause of this?\r\n\r\n(Edit: updated diff based off [1](https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311591619) [2](https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311697202))\r\n```diff\r\n--- a/test/functional/test_framework/test_node.py\r\n+++ b/test/functional/test_framework/test_node.py\r\n@@ -5,6 +5,7 @@\r\n \"\"\"Class for bitcoind node under test\"\"\"\r\n \r\n import contextlib\r\n+from collections import Counter\r\n import decimal\r\n import errno\r\n from enum import Enum\r\n@@ -260,6 +261,7 @@ class TestNode():\r\n         \"\"\"Sets up an RPC connection to the bitcoind process. Returns False if unable to connect.\"\"\"\r\n         # Poll at a rate of four times per second\r\n         poll_per_s = 4\r\n+        ignored_errors = Counter()\r\n         for _ in range(poll_per_s * self.rpc_timeout):\r\n             if self.process.poll() is not None:\r\n                 # Attach abrupt shutdown error/s to the exception message\r\n@@ -308,25 +310,32 @@ class TestNode():\r\n                 return\r\n             except JSONRPCException as e:  # Initialization phase\r\n                 # -28 RPC in warmup\r\n+                if e.error['code'] == -28:\r\n+                    ignored_errors[\"JSONRPCException -28\"] += 1\r\n                 # -342 Service unavailable, RPC server started but is shutting down due to error\r\n-                if e.error['code'] != -28 and e.error['code'] != -342:\r\n+                # - Ignore the exception to properly raise the FailedToStartError.\r\n+                elif e.error['code'] == -342:\r\n+                    ignored_errors[\"JSONRPCException -342\"] += 1\r\n+                else:\r\n                     raise  # unknown JSON RPC exception\r\n-            except ConnectionResetError:\r\n-                # This might happen when the RPC server is in warmup, but shut down before the call to getblockcount\r\n-                # succeeds. Try again to properly raise the FailedToStartError\r\n-                pass\r\n             except OSError as e:\r\n-                if e.errno == errno.ETIMEDOUT:\r\n-                    pass  # Treat identical to ConnectionResetError\r\n+                if e.errno == errno.ECONNRESET:\r\n+                    # This might happen when the RPC server is in warmup, but shut down before the call to getblockcount\r\n+                    # succeeds. Try again to properly raise the FailedToStartError\r\n+                    ignored_errors[\"OSError.ECONNRESET\"] += 1\r\n+                elif e.errno == errno.ETIMEDOUT:\r\n+                    ignored_errors[\"OSError.ETIMEDOUT\"] += 1 # Treat identical to ECONNRESET\r\n                 elif e.errno == errno.ECONNREFUSED:\r\n-                    pass  # Port not yet open?\r\n+                    ignored_errors[\"OSError.ECONNREFUSED\"] += 1 # Port not yet open?\r\n                 else:\r\n                     raise  # unknown OS error\r\n             except ValueError as e:  # cookie file not found and no rpcuser or rpcpassword; bitcoind is still starting\r\n-                if \"No RPC credentials\" not in str(e):\r\n+                if \"No RPC credentials\" in str(e):\r\n+                    ignored_errors[\"missing_credentials\"] += 1\r\n+                else:\r\n                     raise\r\n             time.sleep(1.0 / poll_per_s)\r\n-        self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n+        self._raise_assertion_error(\"Unable to connect to bitcoind after {}s (ignored_errors: {})\".format(self.rpc_timeout, str(dict(ignored_errors))))\r\n \r\n     def wait_for_cookie_credentials(self):\r\n         \"\"\"Ensures auth cookie credentials can be read, e.g. for testing CLI with -rpcwait before RPC connection is up.\"\"\"\r\n```\r\nNot sure if patches like this could be applied to some subset of CI to help debug CI-only issues, slightly unclean, but maybe you've done similar things before?\r\n\r\n~**Notable**: I removed the case for \"-342 Service unavailable, RPC server started but is shutting down due to error\". Seems like we should be failing if the server is shutting down instead of *silently ignoring it*.~",
      "user": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311170636",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311591619,
      "node_id": "IC_kwDOABII586JyBbD",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311591619",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T05:17:47Z",
      "updated_at": "2024-08-27T05:17:47Z",
      "author_association": "MEMBER",
      "body": "> **Notable**: I removed the case for \"-342 Service unavailable, RPC server started but is shutting down due to error\". Seems like we should be failing if the server is shutting down instead of _silently ignoring it_.\r\n\r\nThat'd revert 62c304ea481d474bc87d950e21907b8b05134fe7 and thus break existing tests, no?",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311591619",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311611155,
      "node_id": "IC_kwDOABII586JyGMT",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311611155",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T05:37:12Z",
      "updated_at": "2024-08-27T05:37:12Z",
      "author_association": "MEMBER",
      "body": "For reference: You can use `git log -S \"unique_code_blob\"` to see when (and hopefully why) a piece of code was added. In this case it would be something like:\r\n\r\n```\r\n$ git log -S ' != -342' \r\ncommit 62c304ea481d474bc87d950e21907b8b05134fe7\r\nDate:   Sat Oct 6 13:42:11 2018 +0800\r\n\r\n    tests: Allow closed http server in assert_start_raises_init_error\r\n",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311611155",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311690611,
      "node_id": "IC_kwDOABII586JyZlz",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311690611",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T06:39:07Z",
      "updated_at": "2024-08-27T06:39:07Z",
      "author_association": "MEMBER",
      "body": "Other than that the patch \r\n\r\n> Seen recently here (`wallet_bumpfee.py --descriptors`) https://github.com/bitcoin/bitcoin/actions/runs/9863555844/job/27236587622#step:27:12496:\r\n\r\nThis one looks different, because `node1` never actually starts to start up. It doesn't even get to emit an `10061` error.",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311690611",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311697202,
      "node_id": "IC_kwDOABII586JybMy",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311697202",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T06:43:44Z",
      "updated_at": "2024-08-27T06:43:44Z",
      "author_association": "MEMBER",
      "body": "As for the ignored_errors counter, I presume it will just count `errno.ECONNREFUSED` for WinError 10061?",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311697202",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311773405,
      "node_id": "IC_kwDOABII586Jytzd",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311773405",
      "actor": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T07:31:28Z",
      "updated_at": "2024-08-27T07:31:28Z",
      "author_association": "CONTRIBUTOR",
      "body": "Thanks, I should have searched for why the -342 check was introduced before I suggested removing it. :facepalm: And my git-fu could do with some leveling up, that's impressive how it can single out the right commit.\r\n\r\nUpdated my [suggested diff](https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311170636), bringing back the -342 check.\r\n\r\n> As for the ignored_errors counter, I presume it will just count errno.ECONNREFUSED for WinError 10061?\r\n\r\nYes, that's what [ConnectionRefusedError seems to contain](https://docs.python.org/3/library/exceptions.html#ConnectionRefusedError). Also corrected & updated that part of the diff.",
      "user": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311773405",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311831456,
      "node_id": "IC_kwDOABII586Jy7-g",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311831456",
      "actor": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T08:01:55Z",
      "updated_at": "2024-08-27T08:32:05Z",
      "author_association": "CONTRIBUTOR",
      "body": "> Other than that the patch\r\n> \r\n> > Seen recently here (`wallet_bumpfee.py --descriptors`) https://github.com/bitcoin/bitcoin/actions/runs/9863555844/job/27236587622#step:27:12496:\r\n> \r\n> This one looks different, because `node1` never actually starts to start up. It doesn't even get to emit an `10061` error.\r\n\r\nThe linked log has:\r\n```\r\n node1 2024-07-09T20:27:21.198248Z [shutoff] [D:\\a\\bitcoin\\bitcoin\\src\\init.cpp:386] [Shutdown] Shutdown: done \r\n test  2024-07-09T20:27:21.233000Z TestFramework.node1 (DEBUG): Node stopped \r\n test  2024-07-09T20:27:21.233000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up \r\n node0 2024-07-09T20:27:52.439635Z [scheduler] [D:\\a\\bitcoin\\bitcoin\\src\\net.cpp:2365] [StartExtraBlockRelayPeers] [net] enabling extra block-relay-only peers \r\n node0 2024-07-09T20:42:07.454184Z [scheduler] [D:\\a\\bitcoin\\bitcoin\\src\\net.cpp:2328] [DumpAddresses] [net] Flushed 0 addresses to peers.dat  1ms \r\n node0 2024-07-09T20:57:07.475871Z [scheduler] [D:\\a\\bitcoin\\bitcoin\\src\\net.cpp:2328] [DumpAddresses] [net] Flushed 0 addresses to peers.dat  1ms \r\n test  2024-07-09T21:07:49.462000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 132, in main\r\n                                       self.run_test()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin/test/functional/wallet_bumpfee.py\", line 99, in run_test\r\n                                       test_bumpfee_with_abandoned_descendant_succeeds(self, rbf_node, rbf_node_address, dest_address)\r\n                                     File \"D:\\a\\bitcoin\\bitcoin/test/functional/wallet_bumpfee.py\", line 451, in test_bumpfee_with_abandoned_descendant_succeeds\r\n                                       self.restart_node(1, ['-minrelaytxfee=0.00005'] + self.extra_args[1])\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 602, in restart_node\r\n                                       self.start_node(i, extra_args)\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 554, in start_node\r\n                                       node.wait_for_rpc_connection()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 314, in wait_for_rpc_connection\r\n                                       self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 188, in _raise_assertion_error\r\n                                       raise AssertionError(self._node_msg(msg))\r\n                                   AssertionError: [node 1] Unable to connect to bitcoind after 2400s\r\n```\r\nThe first 2 lines in the excerpt show how node 1 is shutting down right before starting. This made me think of issues reusing TCP ports when restarting a process (stackoverflow [1](https://stackoverflow.com/questions/22549044/why-is-port-not-immediately-released-after-the-socket-closes) [2](https://stackoverflow.com/questions/3229860/what-is-the-meaning-of-so-reuseaddr-setsockopt-option-linux)).\r\n\r\nMaybe it would be better for the test nodes to use new port numbers upon restart, especially for tests like `wallet_bumpfee.py` that use `restart_node`?\r\n\r\nThis could potentially be an issue between two different tests as well, if they shut down/start up quickly enough to still be within the TCP `TIME_WAIT` period.\r\n\r\nEdit: I guess `TIME_WAIT` does not directly explain why connection still fails after *2400s*. But it could be a contributing factor.",
      "user": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311831456",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2311947739,
      "node_id": "IC_kwDOABII586JzYXb",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2311947739",
      "actor": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T08:56:03Z",
      "updated_at": "2024-08-27T08:56:03Z",
      "author_association": "CONTRIBUTOR",
      "body": "(Btw, b22529529823c0cb5916ac318c8536e9107b7e78 did touch code raising `JSONRPCException` `-342` in the beginning of June. Don't see how that change would cause issues, but if it correlates with when you started seeing this, maybe it could be?)",
      "user": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311947739",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2312002464,
      "node_id": "IC_kwDOABII586Jzlug",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2312002464",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T09:21:46Z",
      "updated_at": "2024-08-27T09:21:46Z",
      "author_association": "MEMBER",
      "body": "> This could potentially be an issue between two different tests as well, if they shut down/start up quickly enough to still be within the TCP `TIME_WAIT` period.\r\n\r\nI don't think different tests affect each other, because the test_runner assigns non-overlapping spans of ports for each test case (rpc, p2p, ...).\r\n\r\n> Edit: I guess TIME_WAIT does not directly explain why connection still fails after 2400s. But it could be a contributing factor.\r\n\r\nI don't think Bitcoin Core will re-try to start the HTTP RPC server, so if it fails once, it should fail always?\r\n\r\nHowever, it looks like the node is never started at all. Same in https://github.com/bitcoin/bitcoin/actions/runs/9789643429/job/27029722411?pr=30356\r\n\r\n\r\n\r\n",
      "user": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2312002464",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    },
    {
      "event": "commented",
      "id": 2312067244,
      "node_id": "IC_kwDOABII586Jz1is",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2312067244",
      "actor": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-08-27T09:51:05Z",
      "updated_at": "2024-08-27T09:51:05Z",
      "author_association": "CONTRIBUTOR",
      "body": "> > This could potentially be an issue between two different tests as well, if they shut down/start up quickly enough to still be within the TCP `TIME_WAIT` period.\r\n> \r\n> I don't think different tests affect each other, because the test_runner assigns non-overlapping spans of ports for each test case (rpc, p2p, ...).\r\n\r\nYes, different tests would get different PIDs, which feed into `p2p_port` etc, so port collisions between tests should not happen *unless PIDs are reused within a too short timeperiod*.\r\n\r\n> > Edit: I guess TIME_WAIT does not directly explain why connection still fails after 2400s. But it could be a contributing factor.\r\n> \r\n> I don't think Bitcoin Core will re-try to start the HTTP RPC server, so if it fails once, it should fail always?\r\n\r\nThat is my assumption too.\r\n\r\n> However, it looks like the node is never started at all. Same in https://github.com/bitcoin/bitcoin/actions/runs/9789643429/job/27029722411?pr=30356\r\n\r\nYup, it sure is mysterious. At least having counters for the silent failures could provide some clues. Do you think I should create a PR for https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2311170636?\r\n\r\nSomething definitely seems to be causing bitcoind to keep running but stall somewhere for 2400s without returning an exit code from `.poll()`. Or as you say, Python Popen may be having issues in even starting the process for some reason.\r\n\r\nTangent: In another project, I once saw issues with subprocesses stalling on writing to `stdout` due to the parent process not reading from it quickly enough, so the OS buffer in between the processes would fill up. It was solved by spinning up a dedicated thread in the parent process which continuously read `stdout` from the child. But in our case we seem to mostly be writing subprocess `stdout` & `stderr` to a file, so only running out of disk would potentially cause it to block in a similar fashion to the other project. But running out of disk would hopefully spawn other errors too, making the issue clear.",
      "user": {
        "login": "hodlinator",
        "id": 172445034,
        "node_id": "U_kgDOCkdNag",
        "avatar_url": "https://avatars.githubusercontent.com/u/172445034?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hodlinator",
        "html_url": "https://github.com/hodlinator",
        "followers_url": "https://api.github.com/users/hodlinator/followers",
        "following_url": "https://api.github.com/users/hodlinator/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hodlinator/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hodlinator/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hodlinator/subscriptions",
        "organizations_url": "https://api.github.com/users/hodlinator/orgs",
        "repos_url": "https://api.github.com/users/hodlinator/repos",
        "events_url": "https://api.github.com/users/hodlinator/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hodlinator/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/30390#issuecomment-2312067244",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/30390"
    }
  ]
}